/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ydm_jni_NDKHelper */

#ifndef _Included_com_ydm_jni_NDKHelper
#define _Included_com_ydm_jni_NDKHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ydm_jni_NDKHelper
 * Method:    getStringFormNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ydm_jni_NDKHelper_getStringFormNDK
  (JNIEnv *, jclass);

/*
 * Class:     com_ydm_jni_NDKHelper
 * Method:    getPhoneNumberString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ydm_jni_NDKHelper_getPhoneNumberString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
